import os
import re
import sys

class DuplicateScanner:
    """
    Scans and manages duplicate, temporary, and conflict files across sync vaults. It searches for files that match known patterns for conflicts (e.g., generated by parallel edits), iCloud duplication artifacts, and stale `.tmp` files. It allows the user to interactively review and delete these files before the main sync engine starts, preventing sync thrashing and data corruption.
    """
    def __init__(self, config, logger, disk_io):
        """
        Initializes the DuplicateScanner.

        Args:
            config (SyncConfig): The application configuration containing vault paths and display settings.
            logger (SyncLogger): The logger instance for console and file output.
            disk_io (DiskIO): The disk I/O handler for safely removing files.
        """
        self.config = config
        self.log = logger
        self.io = disk_io

    def scan_and_clean(self):
        """
        Scans all configured vaults for conflict and duplicate files, prompting for deletion. If duplicates are found, it lists them in the console and prompts the user for confirmation to delete them permanently. If confirmed, it attempts to synchronously remove each file and reports the final cleanup status.

        The method iterates through the local vault, iCloud vault, and history directory.
        It identifies files matching three specific regex patterns:
        1. Conflict files (e.g., `_CONFLICT_YYYYMMDD_HHMMSS_ffffff`)
        2. iCloud duplicates (e.g., `filename (1).md`)
        3. Temporary files (e.g., `.tmp` extension)
        """
        conflict_re = re.compile(r'_CONFLICT_\d{8}_\d{6}_\d{6}')
        icloud_dup_re = re.compile(r'\s\(\d+\)\.[^.]+$')
        tmp_re = re.compile(r'\.tmp$')

        duplicates = []
        self.log.info("INFO", "Scanning for conflict/duplicate files...", level="important")

        for root_dir in [self.config.local_vault, self.config.icloud_vault, self.config.history_dir]:
            if not root_dir or not os.path.exists(root_dir):
                continue
            for dirpath, _, filenames in os.walk(root_dir):
                parts = dirpath.replace('\\', '/').lower().split('/')
                if '.trash' in parts:
                    continue
                for f in filenames:
                    if conflict_re.search(f) or icloud_dup_re.search(f) or tmp_re.search(f):
                        duplicates.append(os.path.join(dirpath, f))

        if not duplicates:
            self.log.success("CLEAN", "No duplicates found.", level="important")
            return

        self.log.error("DANGER", f"Found {len(duplicates)} potential conflict/duplicate files.", level="important")
        for p in duplicates:
            self.log.warn("DUPLICATE", self.config.disp(p), level="important")

        self.log.warn("ACTION", "Delete them WITHOUT RECOVERY before sync? (y/N)", level="important")
        sys.stdout.flush()
        try:
            ans = input().strip().lower()
        except KeyboardInterrupt:
            print()
            self.log.warn("INFO", "Interrupted, skipping duplicate cleanup.", level="important")
            return

        if ans in ('y', 'yes'):
            failed_deletions = []
            for p in duplicates:
                self.io.remove_file_sync(p, "Duplicate/Conflict")
                if os.path.exists(p):
                    failed_deletions.append(p)
            if failed_deletions:
                self.log.error("CLEAN", f"Removed {len(duplicates) - len(failed_deletions)} of {len(duplicates)} duplicates; {len(failed_deletions)} could not be removed.", level="important")
                for p in failed_deletions:
                    self.log.warn("FAILED", self.config.disp(p), level="important")
            else:
                self.log.success("CLEAN", "All duplicates removed.", level="important")
        else:
            self.log.warn("INFO", "Skipping duplicate cleanup.", level="important")
        print("-" * 75)
